### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rwhitnah** [NikolaiT/struktur#1]
This is an interesting project. I'm fascinated to see how it develops.

Without a license file, this is, however, unusable by any company or developer - they open themselves up to legal action.

I'd recommend MIT if you're looking for adoption, but Apache 2.0 is also an excellent choice.

Would it be possible to update this repository with a license of some sort, so we can be aware of restrictions before investigating this library further?

Thanks!

**Comment by rwhitnah** [comment]
While I have found https://incolumitas.com/pages/impressum/#impressum , it would need to be actually included with the source code in order to use this code.

If you'd like to make this code effectively public domain, I'd recommend either CC0 or the WTFPL licenses - as they're both explicitly making your code public domain without any assurances of support.

The Unlicense (https://unlicense.org/) is also a way of declaring no copyright interest in your code, without stating anything about the things you've built on top of.

**Comment by NikolaiT** [comment]
Added MIT license
